version: '3.8'

services:
  app:
    build: .
    container_name: msn3-app
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - msn3-network

  webserver:
    image: nginx:latest
    container_name: msn3-webserver
    restart: unless-stopped
    ports:
      - "8098:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - msn3-network

  db:
    image: mysql:8.0
    container_name: msn3-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "33096:3306"
    networks:
      - msn3-network
    volumes:
      - db-data:/var/lib/mysql

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: msn3-phpmyadmin
  #   restart: unless-stopped
  #   ports:
  #     - "8081:80"
  #   environment:
  #     PMA_HOST: db
  #   networks:
  #     - msn3-network

volumes:
  db-data:

networks:
  msn3-network:
